### PR TITLE
Refactor codes to increase readability

### PR DESCRIPTION
**Pull request by gnuhead-chieb**

### CODE REVIEW

**Comment by gnuhead-chieb** [comment]
https://github.com/BiltuDas1/telegram-shell-bot/blob/f86cca27e58f9beb4045372aeff8e6b9500505cc/proc.sh#L132-L145
What is this, it will not run so it is no meaning at all

**Comment by BiltuDas1** [comment]
Actually It will help to scan for malicious urls using VT

Only it will works when it found urls into messages. 

And Thanks for Rewriting whole codes

**Comment by gnuhead-chieb** [comment]
```
until [ "1" == "1" ] 
do
 COMMAND
done
```
will not run any command inside it.
`until` means loop command inside it when return value is `false`(`while` is loop command inside it when return value is `true`)

in this case,using `until` and return value is always true,so any command will not run of-course.

**Comment by BiltuDas1** [comment]
> in this case,using `until` and return value is always true,so any command will not run of-course.

Oh yeah, you are right, just need to replace while with until, thank you for that contribution.

**Comment by gnuhead-chieb** [comment]
if `temp/log.txt` is not need for you,it can be replaced with stdin.

Example:
```
curl --Silent "$fetch/getUpdates" --Output "${WORKINGDIR}/temp/log.txt"
jq '.result[].message.message_id' "${WORKINGDIR}/temp/log.txt" | tail -1
cat "${WORKINGDIR}/temp/log.txt" | tail -1 | grep -c "new_chat_participant"
```
to
```
messagelog=$(curl --Silent "$fetch/getUpdates")
echo "$messagelog" | jq '.result[].message.message_id' | tail -1
echo "$messagelog" | tail -1 | grep -c "new_chat_participant"
```

It will reduce FileIO to can increase efficiency of script.

**Comment by BiltuDas1** [comment]
Nope, temp/log.txt can't be removed, I kept it for future updates. If you do it like this then for multiple processing, it needs to be fetch it multiple times, I kept it like that because some free servers like PythonAnywhere sometime crashes that script, but that main script (run.sh) helps it to restart that bot automatically when it crashes, so that user don't need again turn on manually.

**Comment by gnuhead-chieb** [comment]
okay

**Pull request merged**
